/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M12 5c1.1 0 2 .9 2 2v2.29c.63-.19 1.3-.29 2-.29 3.87 0 7 3.13 7 7s-3.13 7-7 7c-2.79 0-5.2-1.64-6.32-4H4c-1.1 0-2-.9-2-2V7c0-1.1.9-2 2-2zm4 6c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zm-.25 1l.1009.007c.3634.0502.6491.3672.6491.743v3.45l2.24 1.32c.36.21.47.68.24 1.02l-.069.0866c-.2241.2405-.594.3044-.891.1334l-2.52-1.47c-.31-.18-.5-.5-.5-.86v-3.68c0-.41.34-.75.75-.75zM10.09 1c.26 0 .52.11.7.29l.71.71H14c.55 0 1 .45 1 1s-.45 1-1 1H2c-.55 0-1-.45-1-1s.45-1 1-1h2.5l.71-.71c.18-.18.44-.29.7-.29z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const AutoDeleteIcon = (props: IconProps) => renderIcon(props, iconType);
