export { IconProps } from './IconProps';
export { SvgIcon } from './SvgIcon';
export * from './icons/Aliases';
export * from './icons/AV';
export * from './icons/Actions';
export * from './icons/Alert';
export * from './icons/Charts';
export * from './icons/Communication';
export * from './icons/Companies';
export * from './icons/Content';
export * from './icons/CreditCards';
export * from './icons/Custom';
export * from './icons/Device';
export * from './icons/Editor';
export * from './icons/File';
export * from './icons/Hardware';
export * from './icons/Home';
export * from './icons/Image';
export * from './icons/Maps';
export * from './icons/Navigation';
export * from './icons/Notifications';
export * from './icons/Places';
export * from './icons/Social';
export * from './icons/Toggle';
export { categories } from './categories';
