module.exports = {
  collectCoverageFrom: [
    '**/packages/**/src/**/*.{js,jsx,ts,tsx}',
    '!**/?(*.)+(spec|test|stories).{js,ts,mjs,jsx,tsx}',
    '!**/.nx/**',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/public/**',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov'],
  modulePaths: ['<rootDir>'],
  moduleDirectories: ['node_modules'],
  roots: ['<rootDir>'],
  setupFiles: [],
  setupFilesAfterEnv: [
    '<rootDir>/jest.overrides.js',
    '@testing-library/jest-dom',
    'jest-axe/extend-expect',
    '<rootDir>/jest.setup.js',
  ],
  snapshotSerializers: ['@emotion/jest/serializer'],
  testPathIgnorePatterns: [
    '/.cache/',
    '/coverage/',
    '/node_modules/',
    '/public/',
    '/reports/',
    '/static/',
    '/dist/',
    '/archived-packages/',
    '/react-magma-legacy-selects/',
    '<rootDir>/.nx/',
    '\\.d\\.ts$',
  ],
  transform: {
    '^.+\\.(j|t)s(x)?$': ['babel-jest', { cwd: __dirname }],
  },
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^react$': '<rootDir>/node_modules/react',
    '^react-dom$': '<rootDir>/node_modules/react-dom',
    '^react-dom/client$': '<rootDir>/node_modules/react-dom/client',
    '^@testing-library/react$': '<rootDir>/node_modules/@testing-library/react',
  },
};
