/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M21 6c.55 0 1 .45 1 1v2c0 .55-.44 1-1.31 1.01h-2.76c-.61 0-1.08.53-.99 1.13.09.66.09 1.35-.06 2.06-.51 2.51-2.64 4.49-5.19 4.77-3.73.41-6.86-2.59-6.68-6.27.01-.27.05-.53.1-.78-.2.05-.4.08-.61.08C3.12 11 2 9.88 2 8.5S3.12 6 4.5 6c1.11 0 2.04.73 2.37 1.73C8.01 6.66 9.57 6 11.23 6zM11 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3zm0 1c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2zM4.5 8c-.28 0-.5.22-.5.5s.22.5.5.5.5-.22.5-.5-.22-.5-.5-.5z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const SportsIcon = (props: IconProps) => renderIcon(props, iconType);
