/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M17 17v3c0 .55-.45 1-1 1H8c-.55 0-1-.45-1-1v-3h10zM15 3c1.1 0 2 .9 2 2v3c0-.55.45-1 1-1s1 .45 1 1v2.8c0 .13-.01.26-.04.39l-.8 4c-.09.44-.53.8-.98.8H6.82c-.48 0-.89-.33-.98-.8l-.8-4c-.03-.13-.04-.26-.04-.39V5c0-1.1.9-2 2-2zm-1 4H8c-.55 0-1 .45-1 1v1c0 .55.45 1 1 1h6c.55 0 1-.45 1-1V8c0-.55-.45-1-1-1z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const SportsMmaIcon = (props: IconProps) => renderIcon(props, iconType);
