/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M16 17c.55 0 1 .45 1 1s-.45 1-1 1h-1c-1.1 0-2 .9-2 2v1h-2v-1c0-1.1-.9-2-2-2H8c-.55 0-1-.45-1-1s.45-1 1-1zM12 2c3.87 0 7 3.13 7 7s-3.13 7-7 7-7-3.13-7-7 3.13-7 7-7zm0 2C9.24 4 7 6.24 7 9s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zm-2 3c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1zm4 0c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1zm-2-2c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const SportsGolfIcon = (props: IconProps) => renderIcon(props, iconType);
