/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M15.07 13c.32 2.59 1.88 4.79 4.06 6A9.9434 9.9434 0 0113 21.95V13zM11 13v8.95c-2.39-.24-4.53-1.32-6.13-2.95 2.18-1.21 3.74-3.41 4.06-6H11zm-4.09 0c-.33 1.94-1.6 3.57-3.32 4.4-.83-1.29-1.38-2.79-1.54-4.4zm15.04 0c-.16 1.61-.71 3.11-1.54 4.4-1.73-.83-2.99-2.45-3.32-4.4zm-1.54-6.4c.83 1.29 1.38 2.79 1.54 4.4h-4.86c.33-1.95 1.59-3.57 3.32-4.4zm-16.82 0c1.73.83 2.99 2.45 3.32 4.4H2.05c.16-1.61.71-3.11 1.54-4.4zM13 2.05c2.39.24 4.53 1.32 6.13 2.95-2.18 1.21-3.74 3.41-4.06 6H13zm-2 0V11H8.93c-.32-2.59-1.88-4.79-4.06-6C6.46 3.37 8.61 2.29 11 2.05z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const SportsBasketballIcon = (props: IconProps) =>
  renderIcon(props, iconType);
