/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M16 4c.55 0 1 .45 1 1v13c0 .55-.45 1-1 1H8c-.55 0-1-.45-1-1V5c0-.55.45-1 1-1zM4 6c.55 0 1 .45 1 1v9c0 .55-.45 1-1 1s-1-.45-1-1V7c0-.55.45-1 1-1zm16 0c.55 0 1 .45 1 1v9c0 .55-.45 1-1 1s-1-.45-1-1V7c0-.55.45-1 1-1z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const AmpStoriesIcon = (props: IconProps) => renderIcon(props, iconType);
