/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M11.19 1.36c.51-.23 1.1-.23 1.62 0l7 3.11C20.53 4.79 21 5.51 21 6.3V11c0 2.38-.71 4.69-1.92 6.65l-2.9-2.9c1.28-1.94 1.07-4.58-.64-6.29-1.95-1.95-5.12-1.95-7.07 0-1.95 1.95-1.95 5.12 0 7.07 1.71 1.71 4.35 1.93 6.29.64l3.12 3.12C16.33 21.1 14.3 22.44 12 23c-5.16-1.26-9-6.45-9-12V6.3c0-.79.47-1.51 1.19-1.83zM12 9c1.6569 0 3 1.3431 3 3s-1.3431 3-3 3-3-1.3431-3-3 1.3431-3 3-3z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const PolicyIcon = (props: IconProps) => renderIcon(props, iconType);
