import React from 'react';
import { Story, Meta } from '@storybook/react/types-6-0';
import { Combobox, ComboboxProps, MultiComboboxProps } from '.';
import { SelectOptions } from '../Select';
import { LabelPosition } from '../Label';
import { Card } from '../Card';
import { CardBody } from '../Card/CardBody';
import { Heading } from '../Heading';
import { Input } from '../Input';
import { Spacer } from '../Spacer';

const Template: Story<ComboboxProps<SelectOptions>> = args => (
  <Combobox {...args} />
);

export default {
  title: 'Combobox',
  component: Combobox,
  argTypes: {
    labelPosition: {
      control: {
        type: 'select',
        options: LabelPosition,
      },
    },
  },
} as Meta;

export const Default = Template.bind({});
Default.args = {
  labelText: 'Example',
  defaultItems: [
    { label: 'Red', value: 'red' },
    { label: 'Blue', value: 'blue' },
    { label: 'Green', value: 'green' },
  ],
  disableCreateItem: false,
  errorMessage: '',
  helperMessage: '',
  isClearable: false,
  isMulti: false,
  isLoading: false,
};

export const Multi = (props: MultiComboboxProps<SelectOptions>) => {
  return (
    <Combobox
      defaultItems={[
        { label: 'Red', value: 'red' },
        { label: 'Blue', value: 'blue' },
        { label: 'Green', value: 'green' },
        { label: 'Orange', value: 'orange' },
        { label: 'Aqua', value: 'aqua' },
        { label: 'Gold', value: 'gold' },
        { label: 'Periwinkle', value: 'periwinkle' },
        { label: 'Lavender', value: 'lavender' },
        { label: 'Marigold', value: 'marigold' },
      ]}
      {...props}
    />
  );
};
Multi.args = {
  labelText: 'Multi Example',
  isMulti: true,
  isClearable: true,
  errorMessage: '',
  hasPersistentMenu: true,
};

export const ErrorMessage = Template.bind({});
ErrorMessage.args = {
  ...Default.args,
  errorMessage: 'Please fix this error',
};

export const HelperMessage = Template.bind({});
HelperMessage.args = {
  ...Default.args,
  helperMessage: 'This text is helpful',
};

export const Inverse = Template.bind({});
Inverse.args = {
  ...Default.args,
  isInverse: true,
  disabled: false,
};
Inverse.decorators = [
  Story => (
    <Card isInverse>
      <CardBody>
        <Story />
      </CardBody>
    </Card>
  ),
];

export const LeftAlignedLabel = Template.bind({});
LeftAlignedLabel.args = {
  ...Default.args,
  labelPosition: LabelPosition.left,
  errorMessage: 'Please fix this error',
};

export const LeftAlignedLabelWithContainer = Template.bind({});
LeftAlignedLabelWithContainer.args = {
  ...LeftAlignedLabel.args,
};
LeftAlignedLabelWithContainer.decorators = [
  Story => (
    <Card>
      <CardBody style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <Story />
      </CardBody>
    </Card>
  ),
];

export const Typeahead = args => {
  const largeListOfItems = [
    'Aardvark',
    'Aardwolf',
    'Abyssinian',
    'Addax',
    'Adelie Penguin',
    'Affenpinscher',
    'Afghan Hound',
    'African Bullfrog',
    'African Bush Elephant',
    'African Civet',
    'African Clawed Frog',
    'African Forest Elephant',
    'African Grey Parrot',
    'African Palm Civet',
    'African Penguin',
    'African Tree Toad',
    'African Wild Dog',
    'Aidi',
    'Ainu',
    'Airedale Terrier',
    'Airedoodle',
    'Akbash',
    'Akita',
    'Akita Shepherd',
    'Alabai',
    'Alaskan Husky',
    'Alaskan Klee Kai',
    'Alaskan Malamute',
    'Alaskan Shepherd',
    'Albacore Tuna',
    'Albatross',
    'Aldabra Giant Tortoise',
    'Alligator',
    'Alligator Gar',
    'Alpaca',
    'Alpine Dachsbracke',
    'Alpine Goat',
    'Alusky',
    'Amazon Parrot',
    'Amazon River Dolphin (Pink Dolphin)',
    'Ambrosia Beetle',
    'American Alsatian',
    'American Bulldog',
    'American Cocker Spaniel',
    'American Cockroach',
    'American Coonhound',
    'American Eskimo Dog',
    'American Foxhound',
    'American Hairless Terrier',
    'American Leopard Hound',
    'American Pit Bull Terrier',
    'American Pygmy Goat',
    'American Robin',
    'American Staffordshire Terrier',
    'American Toad',
    'American Water Spaniel',
    'Amur Leopard',
    'Anatolian Shepherd Dog',
    'Anchovies',
    'Angelfish',
    'Anglerfish',
    'Angora Goat',
    'Ant',
    'Antarctic scale worm',
    'Anteater',
    'Antelope',
    'Appenzeller Dog',
    'Apple Head Chihuahua',
    'Arapaima',
    'Arctic Fox',
    'Arctic Hare',
    'Arctic Wolf',
    'Arizona Bark Scorpion',
    'Armadillo',
    'Armyworm',
    'Asian Elephant',
    'Asian Giant Hornet',
    'Asian Palm Civet',
    'Asiatic Black Bear',
    'Aurochs',
    'Aussiedoodle',
    'Aussiedor',
    'Australian Bulldog',
    'Australian Cattle Dog',
    'Australian Gecko',
    'Australian Kelpie Dog',
    'Australian Labradoodle',
    'Australian Mist',
    'Australian Retriever',
    'Australian Shepherd',
    'Australian Terrier',
    'Avocet',
    'Axolotl',
    'Barracuda',
    'Barramundi Fish',
    'Barred Owl',
    'Basenji Dog',
    'Basking Shark',
    'Bassador',
    'Basset Fauve de Bretagne',
    'Basset Hound',
    'Bassetoodle',
    'Bat',
    'Bavarian Mountain Hound',
    'Bea-Tzu',
    'Beabull',
    'Beagador',
    'Beagle',
    'Beagle Shepherd',
    'Beaglier',
    'Beago',
    'Bear',
    'Bearded Collie',
    'Bearded Dragon',
    'Beaski',
    'Beauceron',
    'Beaver',
    'Bed Bugs',
    'Bedlington Terrier',
    'Bee',
    'Beefalo',
    'Beetle',
    'Belgian Shepherd',
    'Belgian Tervuren',
    'Beluga Sturgeon',
    'Bengal Tiger',
    'Bergamasco',
    'Berger Picard',
    'Bernedoodle',
    'Bernese Mountain Dog',
    'Bernese Shepherd',
    'Bichir',
    'Bichon Frise',
    'Bichpoo',
    'Biewer Terrier',
    'Bighorn Sheep',
    'Bilby',
    'Binturong',
    'Bird',
    'Bird Of Paradise',
    'Birman',
    'Biscuit Beetle',
    'Bison',
    'Black And Tan Coonhound',
    'Black Marlin',
    'Black Rhinoceros',
    'Black Russian Terrier',
    'Black Wasp',
    'Black Widow Spider',
    'Black-Footed Ferret',
    'Blackpoll Warbler',
    'Blister Beetle',
    'Blobfish',
    'Bloodhound',
    'Blue Belly Lizard',
    'Blue grosbeak',
    'Blue Iguana',
    'Blue Jay',
    'Blue Lacy Dog',
    'Blue Picardy Spaniel',
    'Blue Shark',
    'Blue Whale',
    'Blue-Ringed Octopus',
    'Bluefin Tuna',
    'Bluetick Coonhound',
    'Bobcat',
    'Bobolink',
    'Boggle',
    'Boglen Terrier',
    'Bolognese Dog',
    'Bombay',
    'Bongo',
    'Bonito Fish',
    'Bonnethead Shark',
    'Bonobo',
    'Booby',
    'Borador',
    'Border Collie',
    'Border Terrier',
    'Bordoodle',
    'Borkie',
    'Bornean Orang-utan',
    'Borneo Elephant',
    'Boston Terrier',
    'Bottlenose Dolphin',
    'Bouvier Des Flandres',
    'Bowfin',
    'Bowhead Whale',
    'Box Turtle',
    'Boxador',
    'Boxer Dog',
    'Boxerdoodle',
    'Boxsky',
    'Boxweiler',
    'Boykin Spaniel',
    'Brazilian Terrier',
    'British Timber',
    'Brittany',
    'Brookesia Micra',
    'Brown Bear',
    'Brown Hyena',
    'Brug',
    'Brussels Griffon',
    'Budgerigar',
    'Buffalo',
    'Bull Shark',
    'Bull Terrier',
    'Bulldog',
    'Bullfrog',
    'Bullmastiff',
    'Bumblebee',
    'Burmese',
    'Burmese Python',
    'Burrowing Frog',
    'Burrowing Owl',
    'Bush Baby',
    'Butterfly',
    'Butterfly Fish',
    'Cicada',
    'Cichlid',
    'Clouded Leopard',
    'Clownfish',
    'Clumber Spaniel',
    'Coati',
    'Cockalier',
    'Cockapoo',
    'Cockatiel',
    'Cockatoo',
    'Cocker Spaniel',
    'Cockroach',
    'Codfish',
    'Coelacanth',
    'Collared Peccary',
    'Collie',
    'Colossal Squid',
    'Common Buzzard',
    'Common Frog',
    'Common Furniture Beetle',
    'Common House Spider',
    'Common Loon',
    'Common Raven',
    'Common Toad',
    'Cookiecutter Shark',
    "Cooper's Hawk",
    'Coral',
    'Corgidor',
    'Corgipoo',
    'Corkie',
    'Corman Shepherd',
    'Corn Rex Cat (Cornish Rex)',
    'Coton de Tulear',
    'Cotton-top Tamarin',
    'Cougar',
    'Cow',
    'Coyote',
    'Crab',
    'Crab Spider',
    'Crab-Eating Macaque',
    'Crabeater Seal',
    'Crane',
    'Crappie Fish',
    'Crested Penguin',
    'Cricket',
    'Crocodile',
    'Cross Fox',
    'Cross River Gorilla',
    'Crow',
    'Cuckoo',
    'Curly Coated Retriever',
    'Cuscus',
    'Cuttlefish',
    'Czechoslovakian Wolfdog',
    'Dachsador',
    'Dachshund',
    'Dalmadoodle',
    'Dalmador',
    'Dalmatian',
    'Dapple Dachshund',
    "Darwin's fox",
    "Darwin's Frog",
    'Deathwatch Beetle',
    'Deer',
    'Desert Locust',
    'Desert Rain Frog',
    'Desert Tortoise',
    'Deutsche Bracke',
    'Devils Coach Horse Beetle',
    'Devon Rex',
    'Dhole',
    'Dik-Dik',
    'Dingo',
    'Discus',
    'Doberman Pinscher',
    'Dodo',
    'Dog',
    'Dogo Argentino',
    'Dogue De Bordeaux',
    'Dolphin',
    'Donkey',
    'Dorgi',
    'Dorkie',
    'Dormouse',
    'Double Doodle',
    'Douc',
    'Doxiepoo',
    'Doxle',
    'Draco volans',
    'Dragonfish',
    'Dragonfly',
    'Drever',
    'Drum Fish',
    'Duck',
    'Dugong',
    'Dung Beetle',
    'Dunker',
    'Dusky Dolphin',
    'Eastern Bluebird',
    'Eastern Fence Lizard',
    'Eastern Gorilla',
    'Eastern Lowland Gorilla',
    'Eastern Phoebe',
    'Echidna',
    'Edible Frog',
    'Eel',
    'Egyptian Mau',
    'Electric Eel',
    'Elephant',
    'Elephant Seal',
    'Elephant Shrew',
    'Elk',
    'Emperor Penguin',
    'Emperor Tamarin',
    'English Bulldog',
    'English Cocker Spaniel',
    'English Cream Golden Retriever',
    'English Foxhound',
    'English Pointer',
    'English Setter',
    'English Shepherd',
    'English Springer Spaniel',
    'Entlebucher Mountain Dog',
    'Epagneul Pont Audemer',
    'Ermine',
    'Eskimo Dog',
    'Eskipoo',
    'Estrela Mountain Dog',
    'Eurasian Nuthatch',
    'Falcon',
    'Fallow deer',
    'False Killer Whale',
    'False Widow Spider',
    'Fangtooth',
    'Feist',
    'Fennec Fox',
    'Ferret',
    'Ferruginous Hawk',
    'Fiddler Crab',
    'Field Spaniel',
    'Fila Brasileiro',
    'Fin Whale',
    'Finnish Spitz',
    'Fire salamander',
    'Fire-Bellied Toad',
    'Firefly',
    'Fisher Cat',
    'Fishing Cat',
    'Flamingo',
    'Flat-Coated Retriever',
    'Flea',
    'Florida Gar',
    'Florida Panther',
    'Flounder',
    'Flowerhorn Fish',
    'Fly',
    'Flying Fish',
    'Flying Lemur',
    'Flying Squirrel',
    'Formosan Mountain Dog',
    'Fossa',
    'Fox',
    'Fox Squirrel',
    'Fox Terrier',
    'French Bulldog',
    'Frenchton',
    'Frengle',
    'Frigatebird',
    'Frilled Lizard',
    'Frilled Shark',
    'Frog',
    'Frogfish',
    'Fruit Bat',
    'Fruit Fly',
    'Fur Seal',
    'Gerberian Shepsky',
    'Gerbil',
    'German Pinscher',
    'German Shepherd Guide',
    'German Sheppit',
    'German Sheprador',
    'German Shorthaired Pointer',
    'German Spitz',
    'Gharial',
    'Ghost Crab',
    'Giant African Land Snail',
    'Giant Armadillo',
    'Giant Clam',
    'Giant Panda Bear',
    'Giant Salamander',
    'Giant Schnauzer',
    'Giant Schnoodle',
    'Gibbon',
    'Gila Monster',
    'Giraffe',
    'Glass Frog',
    'Glass Lizard',
    'Glechon',
    'Glen Of Imaal Terrier',
    'Glow Worm',
    'Gnat',
    'Goat',
    'Goberian',
    'Goblin Shark',
    'Goldador',
    'Golden Dox',
    'Golden Lion Tamarin',
    'Golden Masked Owl',
    'Golden Newfie',
    'Golden Oriole',
    'Golden Pyrenees',
    'Golden Retriever',
    'Golden Saint',
    'Golden Shepherd',
    'Golden-Crowned Flying Fox',
    'Goldendoodle',
    'Goldfish',
    'Goliath Frog',
    'Goose',
    'Gopher',
    'Gopher Tortoise',
    'Gordon Setter',
    'Gorilla',
    'Gouldian Finch',
    'Grasshopper',
    'Grasshopper Mouse',
    'Gray Fox',
    'Gray Tree Frog',
    'Great Blue Heron',
    'Great Crested Flycatcher',
    'Great Dane',
    'Great Danoodle',
    'Great Pyrenees',
    'Great White Shark',
    'Greater Swiss Mountain Dog',
    'Green Anole',
    'Green Bee-Eater',
    'Green Frog',
    'Green Tree Frog',
    'Greenland Dog',
    'Greenland Shark',
    'Grey Mouse Lemur',
    'Grey Reef Shark',
    'Grey Seal',
    'Greyhound',
    'Griffonshire',
    'Grizzly Bear',
    'Groenendael',
    'Grouse',
    'Haddock',
    'Hagfish',
    'Hammerhead Shark',
    'Hamster',
    'Harbor Seal',
    'Hare',
    'Harp Seal',
    'Harpy Eagle',
    'Harrier',
    'Harris Hawk',
    'Havapoo',
    'Havashire',
    'Hawaiian Crow',
    'Hawaiian Monk Seal',
    'Hedgehog',
    'Hellbender',
    'Hercules Beetle',
    'Hermit Crab',
    'Heron',
    'Herring',
    'Hippopotamus',
    'Hoary Bat',
    'Hokkaido',
    'Honduran White Bat',
    'Honey Badger',
    'Honey Bee',
    'Hooded Seal',
    'Hoopoe',
    'Horn Shark',
    'Horned Frog',
    'Horned Lizard',
    'Horse',
    'Horsefly',
    'Horseshoe Crab',
    'House Finch',
    'House wren',
    'Housefly',
    'Howler Monkey',
    'Human',
    'Humboldt Penguin',
    'Humboldt Squid',
    'Hummingbird',
    'Humpback Whale',
    'Huntaway',
    'Huntsman Spider',
    'Huskador',
    'Huskita',
    'Husky',
    'Husky Jack',
    'Ibex',
    'Ibis',
    'Ibizan Hound',
    'Icelandic Sheepdog',
    'Iguana',
    'Immortal Jellyfish',
    'Impala',
    'Imperial Moth',
    'Indian Elephant',
    'Indian Giant Squirrel',
    'Indian Palm Squirrel',
    'Indian Rhinoceros',
    'Indian Star Tortoise',
    'Indochinese Tiger',
    'Indri',
    'Insects',
    'Irish Doodle',
    'Irish Setter',
    'Irish Terrier',
    'Irish Water Spaniel',
    'Irish WolfHound',
    'Italian Greyhound',
    'Jacana',
    'Jack Russell',
    'Jackabee',
    'Jackal',
    'Jackdaw',
    "Jackson's Chameleon",
    'Jaguar',
    'Jaguarundi Cat',
    'Japanese Beetle',
    'Japanese Chin',
    'Japanese Macaque',
    'Japanese Spitz',
    'Japanese Terrier',
    'Javan Rhinoceros',
    'Javanese',
    'Jellyfish',
    'Jerboa',
    'Joro Spider',
    'Jumping Spider',
    'Kai Ken',
    'Kakapo',
    'Kangal',
    'Kangaroo',
    'Kangaroo Rat',
    'Keel-Billed Toucan',
    'Keeshond',
    'Kerry Blue Terrier',
    'Key Deer',
    'Kiko Goat',
    'Killer Whale',
    'Kinder Goat',
    'King Cobra',
    'King Crab',
    'King Penguin',
    'King Shepherd',
    'Kingfisher',
    'Kinkajou',
    'Kishu',
    'Kiwi',
    'Koala',
    'Kodkod',
    'Koi Fish',
    'Komodo Dragon',
    'Kooikerhondje',
    'Kookaburra',
    'Koolie',
    'Krill',
    'Kudu',
    'Kuvasz',
    'Labahoula',
    'Labmaraner',
    'Labradoodle',
    'Labrador Retriever',
    'Ladybug',
    'Lemur',
    'Leonberger',
    'Leopard',
    'Leopard Cat',
    'Leopard Gecko',
    'Leopard Seal',
    'Leopard Tortoise',
    'Lion’s Mane Jellyfish',
    'Lizard',
    'Locust',
    'Long-Haired Rottweiler',
    'Longnose Gar',
    'Lorikeet',
    'Lowchen',
    'Lynx',
    'Lyrebird',
    'Malayan Civet',
    'Maltese Shih Tzu',
    'Maltipoo',
    'Man of War Jellyfish',
    'Manatee',
    'Mantella Frog',
    'Marabou Stork',
    'Marine Toad',
    'Markhor',
    'Masked Palm Civet',
    'Mayfly',
    'Megalodon',
    'Mexican Free-Tailed Bat',
    'Millipede',
    'Miniature Bull Terrier',
    'Mole',
    'Mole Cricket',
    'Monarch Butterfly',
    'Mongoose',
    'Mongrel',
    'Moorhen',
    'Moscow Watchdog',
    'Moth',
    'Mudi',
    'Mule',
    'Muskox',
    'Muskrat',
    'Naked Mole Rat',
    'Narwhal',
    'Neanderthal',
    'Neapolitan Mastiff',
    'Nebelung',
    'Newfoundland',
    'Newfypoo',
    'Newt',
    'Nicobar pigeon',
    'Nigerian Goat',
    'Nightingale',
    'Nile Crocodile',
    'No See Ums',
    'Norfolk Terrier',
    'North American Black Bear',
    'Northern Cardinal',
    'Northern Fur Seal',
    'Norwegian Elkhound',
    'Norwegian Forest',
    'Norwegian Lundehund',
    'Numbat',
    'Ocelot',
    'Octopus',
    'Okapi',
    'Old English Sheepdog',
    'Olm',
    'Opossum',
    'Orang-utan',
    'Orb Weaver',
    'Oscar Fish',
    'Ostrich',
    'Otter',
    'Otterhound',
    'Oyster',
    'Oyster Toadfish',
    'Paddlefish',
    'Pademelon',
    'Painted Turtle',
    'Pangolin',
    'Panther',
    'Papillon',
    'Parakeet',
    'Parrot',
    'Parrotlet',
    'Parson Russell Terrier',
    'Patas Monkey',
    'Patterdale Terrier',
    'Peacock',
    'Peacock Butterfly',
    'Peacock Spider',
    'Peagle',
    'Peekapoo',
    'Pekingese',
    'Pelican',
    'Pembroke Welsh Corgi',
    'Penguin',
    'Pere Davids Deer',
    'Peregrine Falcon',
    'Persian',
    'Petite Goldendoodle',
    'Pheasant',
    'Pied Tamarin',
    'Pig',
    'Pigeon',
    'Pika',
    'Pike Fish',
    'Pileated Woodpecker',
    'Pine Marten',
    'Pink Fairy Armadillo',
    'Piranha',
    'Pit Bull',
    'Pitador',
    'Pitsky',
    'Platypus',
    'Pocket Beagle',
    'Pocket Pitbull',
    'Pointer',
    'Poison Dart Frog',
    'Polar Bear',
    'Polish Lowland Sheepdog',
    'Polyphemus moth',
    'Pomapoo',
    'Pomchi',
    'Pomeagle',
    'Pomeranian',
    'Pomsky',
    'Pond Skater',
    'Poochon',
    'Poodle',
    'Poogle',
    'Pool Frog',
    'Porbeagle Shark',
    'Porcupine',
    'Porpoise',
    'Possum',
    'Potoroo',
    'Prairie Dog',
    'Prairie Rattlesnake',
    'Prawn',
    'Praying Mantis',
    'Proboscis Monkey',
    'Pronghorn',
    'Pudelpointer',
    'Puffin',
    'Pug',
    'Pugapoo',
    'Puggle',
    'Pugshire',
    'Puma',
    'Pumi',
    'Purple Finch',
    'Quagga',
    'Quail',
    'Quetzal',
    'Quokka',
    'Quoll',
    'Raccoon',
    'Raccoon Dog',
    'Radiated Tortoise',
    'Ragamuffin',
    'Ragdoll',
    'Raggle',
    'Rattlesnake',
    'Red Finch',
    'Red Fox',
    'Red Knee Tarantula',
    'Red Panda',
    'Red Squirrel',
    'Red Wolf',
    'Reindeer',
    'Rhinoceros',
    'Ringed Kingfisher',
    'River Otter',
    'Robin',
    'Rock Crab',
    'Rock Hyrax',
    'Rockfish',
    'Rockhopper Penguin',
    'Rodents',
    'Roe Deer',
    'Rooster',
    'Rose-breasted Grosbeak',
    'Roseate Spoonbill',
    'Rottsky',
    'Rottweiler',
    'Ruby-Throated Hummingbird',
    'Russian Bear Dog',
    'Russian Blue',
    'Russian Tortoise',
    'Sable',
    'Saint Berdoodle',
    'Sawfish',
    'Schneagle',
    'Sea Anemone',
    'Sea Eagle',
    'Sea Lion',
    'Sea Otter',
    'Sea Urchin',
    'Seagull',
    'Seahorse',
    'Sei Whale',
    'Senegal Parrot',
    'Shark',
    'Siberian Ibex',
    'Siberpoo',
    'Silky Terrier',
    'Skink Lizard',
    'Skye Terrier',
    'Snapping Turtle',
    'Snowshoe',
    'Snowy Owl',
    'Spanish Mastiff',
    'Sperm Whale',
    'Spotted Lanternfly',
    'Stabyhoun',
    'Starfish',
    'Stick Insect',
    'Stoat',
    'Sumatran Elephant',
    'Sumatran Rhinoceros',
    'Swedish Vallhund',
    'Taco Terrier',
    'Tamaskan',
    'Tang',
    'Tapanuli Orang-utan',
    'Tapir',
    'Tarantula Hawk',
    'Tarpon',
    'Tarsier',
    'Tasmanian Devil',
    'Tasmanian Tiger',
    'Tawny Owl',
    'Teddy Bear Hamster',
    'Teddy Roosevelt Terrier',
    'Tenterfield Terrier',
    'Tetra',
    'Texas Heeler',
    'Thai Ridgeback',
    'Thorny Devil',
    'Tibetan Fox',
    'Tibetan Mastiff',
    'Tibetan Spaniel',
    'Tibetan Terrier',
    'Tick',
    'Tiffany',
    'Tiger',
    'Tiger Beetle',
    'Tiger Moth',
    'Tiger Salamander',
    'Tiger Shark',
    'Toadfish',
    'Torkie',
    'Toucan',
    'Toy Fox Terrier',
    'Toy Poodle',
    'Transylvanian Hound',
    'Tree Kangaroo',
    'Tree swallow',
    'Treeing Tennessee Brindle',
    'Treeing Walker Coonhound',
    'Tropicbird',
    'Tsetse Fly',
    'Tuatara',
    'Tuna',
    'Turkey',
    'Turkish Angora',
    'Uakari',
    'Uguisu',
    'Umbrellabird',
    'Utonagan',
    'Vampire Bat',
    'Vampire Squid',
    'Vaquita',
    'Venus Flytrap',
    'Vervet Monkey',
    'Vinegaroon',
    'Vizsla',
    'Volpino Italiano',
    'Vulture',
    'White Butterfly',
    'White Rhinoceros',
    'White Tiger',
    'White-Faced Capuchin',
    'White-tail deer',
    'White-Tailed Eagle',
    'Whoodle',
    'Whooping Crane',
    'Wild Boar',
    'Wildebeest',
    'Willow Warbler',
    'Wire Fox Terrier',
    'Wolf',
    'Wolf Eel',
    'Wolf Spider',
    'Wolffish',
    'Wolverine',
    'Wombat',
    'Wood Bison',
    'Wood Frog',
    'Wood Turtle',
    'Woodlouse',
    'Woodlouse Spider',
    'Woodpecker',
    'Woodrat',
    'Woolly Mammoth',
    'Woolly Monkey',
    'Worm',
    'Wrasse',
    'Writing Spider',
    'Wyoming Toad',
    'X-Ray Tetra',
    'Xerus',
    'Xoloitzcuintli',
    'Yak',
    'Yakutian Laika',
    'Yellow Sac Spider',
    'Yellow-Eyed Penguin',
    'Yellowfin Tuna',
    'Yeti Crab',
    'Yoranian',
    'Yorkie Bichon',
    'Yorkie-poo',
    'Yorkshire Terrier',
    'Zebra',
    'Zebra Finch',
    'Zebra Mussels',
    'Zebra Pleco',
    'Zebu',
    'Zonkey',
    'Zorse',
  ];

  const mediumListOfItems = [
    'Aardvark',
    'Aardwolf',
    'Abyssinian',
    'Addax',
    'Adelie Penguin',
    'Affenpinscher',
    'Afghan Hound',
    'African Bullfrog',
    'African Bush Elephant',
    'African Civet',
    'African Clawed Frog',
    'African Forest Elephant',
    'African Grey Parrot',
    'African Palm Civet',
    'African Penguin',
    'African Tree Toad',
    'African Wild Dog',
    'Aidi',
    'Ainu',
    'Airedale Terrier',
    'Airedoodle',
    'Akbash',
    'Akita',
    'Akita Shepherd',
    'Alabai',
    'Alaskan Husky',
    'Alaskan Klee Kai',
    'Alaskan Malamute',
    'Alaskan Shepherd',
    'Albacore Tuna',
    'Albatross',
    'Aldabra Giant Tortoise',
    'Alligator',
    'Alligator Gar',
    'Alpaca',
    'Alpine Dachsbracke',
    'Alpine Goat',
    'Alusky',
    'Amazon Parrot',
    'Amazon River Dolphin (Pink Dolphin)',
    'Ambrosia Beetle',
    'American Alsatian',
    'American Bulldog',
    'American Cocker Spaniel',
    'American Cockroach',
    'American Coonhound',
    'American Eskimo Dog',
    'American Foxhound',
    'American Hairless Terrier',
    'American Leopard Hound',
    'American Pit Bull Terrier',
    'American Pygmy Goat',
    'American Robin',
    'American Staffordshire Terrier',
    'American Toad',
    'American Water Spaniel',
    'Amur Leopard',
    'Anatolian Shepherd Dog',
    'Anchovies',
    'Angelfish',
    'Anglerfish',
    'Angora Goat',
    'Ant',
    'Antarctic scale worm',
    'Anteater',
    'Antelope',
    'Appenzeller Dog',
    'Apple Head Chihuahua',
    'Arapaima',
    'Arctic Fox',
    'Arctic Hare',
    'Arctic Wolf',
    'Arizona Bark Scorpion',
    'Armadillo',
    'Armyworm',
    'Asian Elephant',
    'Asian Giant Hornet',
    'Asian Palm Civet',
    'Asiatic Black Bear',
    'Aurochs',
    'Aussiedoodle',
    'Aussiedor',
    'Australian Bulldog',
    'Australian Cattle Dog',
    'Australian Gecko',
    'Australian Kelpie Dog',
    'Australian Labradoodle',
    'Australian Mist',
    'Australian Retriever',
    'Australian Shepherd',
    'Australian Terrier',
    'Avocet',
    'Axolotl',
  ];

  const [suggestedItems, setSuggestedItems] = React.useState([]);
  const [selectedItems, updateSelectedItems] = React.useState([]);
  const [isLoading, setIsLoading] = React.useState(true);
  const [inputQuery, setInputQuery] = React.useState('');
  const dataSet = args.largeDataSet ? largeListOfItems : mediumListOfItems;

  function handleSelectedItemsChange(changes) {
    updateSelectedItems(changes.selectedItems);
  }

  function onInputKeyPress(event) {
    setInputQuery(event.target.value + event.key);
  }

  function onInputValueChange(event) {
    setInputQuery(event.inputValue);
  }

  React.useEffect(() => {
    setTimeout(() => {
      setIsLoading(true);
    }, 100);

    setTimeout(() => {
      const matches = dataSet.filter(item => {
        return item.toLowerCase().includes(inputQuery.toLowerCase());
      });
      const newSuggestedItems = matches.slice(0, 5).map(item => {
        return { label: item, value: item };
      });

      setTimeout(() => {
        setSuggestedItems(newSuggestedItems);
        setIsLoading(false);
      }, 100);
    }, 1000);
  }, [inputQuery]);

  return (
    <Combobox
      {...args}
      items={suggestedItems}
      isLoading={isLoading}
      labelText="Typeahead Example - Animals"
      onInputKeyPress={onInputKeyPress}
      onInputValueChange={onInputValueChange}
      onSelectedItemsChange={handleSelectedItemsChange}
    />
  );
};

Typeahead.args = {
  isTypeahead: true,
  isClearable: true,
  isMulti: true,
  disableCreateItem: true,
  largeDataSet: false,
};

export const FullPageExample = args => {
  return (
    <>
      <Heading level={1}>Confirm Adoption</Heading>
      <Combobox
        labelText="Select the format(s) for which you would like to review pricing *"
        defaultItems={[
          { label: 'eBook', value: 'eBook' },
          { label: 'Paperback', value: 'paperback' },
          { label: 'Hardcover', value: 'hardcover' },
          { label: 'Online Homework Platform', value: 'onlinehwplt' },
        ]}
        isMulti
        hasPersistentMenu
        placeholder="Select format(s)"
        isClearable
        disableCreateItem
      />
      <Spacer size={16} />
      <Input
        labelText="What is the name and number of the course you are requesting this title for? *"
        maxLength={100}
        placeholder="SWEN101"
      />
      <Spacer size={16} />
      <Combobox
        labelText="What term will you be teaching? *"
        defaultItems={[
          { label: 'Spring', value: 'Spring' },
          { label: 'Summer', value: 'Summer' },
          { label: 'Fall', value: 'Fall' },
          { label: 'Winter', value: 'Winter' },
        ]}
        isMulti
        hasPersistentMenu
        placeholder="Select term"
        disableCreateItem
      />
      <Spacer size={16} />
      <Combobox
        labelText="What is your role in selecting a title for this course?"
        defaultItems={[
          { label: 'One', value: 'one' },
          { label: 'Two', value: 'two' },
          { label: 'Three', value: 'three' },
          { label: 'Four', value: 'four' },
        ]}
        placeholder="Select role"
        disableCreateItem
      />
      <Spacer size={16} />
    </>
  );
};
FullPageExample.parameters = { controls: { exclude: ['labelPosition'] } };
