/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import * as React from 'react';
import { IconProps } from '../../IconProps';
import { EventIcon } from '../Actions/EventIcon';
export const CalendarIcon = (props: IconProps) => {
  if (process.env.NODE_ENV === 'development') {
    console.warn('CalendarIcon has been deprecated');
  }
  return <EventIcon {...props} />;
};
