/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import * as React from 'react';
import { IconProps } from '../../IconProps';
import { ArrowDropDownIcon } from '../Navigation/ArrowDropDownIcon';
export const CaretDownIcon = (props: IconProps) => {
  if (process.env.NODE_ENV === 'development') {
    console.warn('CaretDownIcon has been deprecated');
  }
  return <ArrowDropDownIcon {...props} />;
};
