/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import * as React from 'react';
import { IconProps } from '../../IconProps';
import { ArrowLeftIcon } from '../Navigation/ArrowLeftIcon';
export const CaretLeftIcon = (props: IconProps) => {
  if (process.env.NODE_ENV === 'development') {
    console.warn('CaretLeftIcon has been deprecated');
  }
  return <ArrowLeftIcon {...props} />;
};
