/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import * as React from 'react';
import { IconProps } from '../../IconProps';
import { ArrowRightIcon } from '../Navigation/ArrowRightIcon';
export const CaretRightIcon = (props: IconProps) => {
  if (process.env.NODE_ENV === 'development') {
    console.warn('CaretRightIcon has been deprecated');
  }
  return <ArrowRightIcon {...props} />;
};
