/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import * as React from 'react';
import { IconProps } from '../../IconProps';
import { InfoIcon } from '../Actions/InfoIcon';
export const Info2Icon = (props: IconProps) => {
  if (process.env.NODE_ENV === 'development') {
    console.warn('Info2Icon has been deprecated');
  }
  return <InfoIcon {...props} />;
};
