/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M11 18l6 3h-4v2l-6-3h4v-2zm4.89-17c.93 0 1.74.65 1.95 1.56l1.9 8.44H19c-2.21 0-4 1.79-4 4v1H7.82C7.4 17.16 6.3 18 5 18c-1.84 0-3.3-1.66-2.95-3.56.22-1.18 1.17-2.15 2.35-2.38 1.56-.3 2.94.6 3.42 1.94h5.27c.38-2.27 2.03-4.1 4.19-4.75h.01L15.89 3H13c-.55 0-1-.45-1-1s.45-1 1-1zM19 12c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zM5 14c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1zm14 0c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const ElectricScooterIcon = (props: IconProps) =>
  renderIcon(props, iconType);
