/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d:
        'M12 3c.68 0 1.35.09 2 .26V10h5.91c.05.39.09.79.09 1.2 0 3.18-2.45 6.92-7.33 11.23-.38.33-.95.33-1.33 0C6.45 18.12 4 14.38 4 11.2 4 6.22 7.8 3 12 3zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm9.12-7.54l1.42 1.42L20.41 5l2.13 2.12-1.42 1.42L19 6.41l-2.12 2.13-1.42-1.42L17.59 5l-2.13-2.12 1.42-1.42L19 3.59l2.12-2.13z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const WrongLocationIcon = (props: IconProps) =>
  renderIcon(props, iconType);
