/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from '../../IconProps';
import { renderIcon } from '../../SvgIcon';
const iconType = {
  viewBox: '0 0 24 24',
  paths: [
    {
      d: 'M17.5556 17.5556H6.4444V2H2v20h20V2h-4.4444z',
      fillRule: 'evenodd',
    },
  ],
  circles: [],
};

export const WlUseItIcon = (props: IconProps) => renderIcon(props, iconType);
