name: Build and Deploy Docs for V2.6.0
# This workflow is triggered on push to the chore/deploy-v2-docs branch.

on:
  push:
    branches:
      - chore/deploy-v2-docs

jobs:
  build-deploy-v2-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: react-magma-dom@2.6.0
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Add import statement in index.js
        run: |
          echo "import _styled from '@emotion/styled';" | cat - packages/react-magma-dom/dist/esm/index.js > temp && mv temp packages/react-magma-dom/dist/esm/index.js

      - name: Build Docs
        run:  NODE_OPTIONS=--openssl-legacy-provider npm run build:docs
        env:
          PATH_PREFIX: /version/2.6.0

      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: 2.6.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
