name: Build and Deploy Docs for V3.11.0
# This workflow is triggered on push to the chore/deploy-v3-docs branch .

on:
  push:
    branches:
      - chore/deploy-v3-docs

jobs:
  deploy-v3-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: react-magma-dom@3.11.0
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Configure NPM
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc

      - name: Get Alias
        id: info
        run: |
          echo "::set-output name=alias::$(npm run --silent getAlias)"
          echo "::set-output name=version::$(npm run --silent getVersion)"

      - name: Build Docs
        run: npm run build:docs
        env:
          PATH_PREFIX: /version/${{ matrix.version }}

      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ matrix.version }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
