name: Testing-Local
on:
  push:
    branches:
      - build/Storybook_dev_deploy
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Update NPM version
        run: npm install -g "npm@^7.6.3"
      - name: Install
        run: npm ci
      - name: Build Docs
        run: npm run build:docs
      - name: Build Storybook
        run: npm run build:storybook
      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: next
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      # - name: Deploy Dev Storybook to Netlify
      #   uses: nwtgck/actions-netlify@v1.1
      #   with:
      #     publish-dir: './storybook-static'
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     enable-pull-request-comment: true
      #     enable-commit-comment: true
      #     overwrites-pull-request-comment: false
      #     alias: storybook-preview-dev
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
