name: preview-v2
on:
  pull_request:
    branches:
      - v2/dev
      - v2/main
    types: [opened, edited, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Update NPM version
        run: npm install -g "npm@^11.11.0"
      - name: Check NPM version
        run: npm -v
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Test
        run: npm test
      - name: Build Storybook
        run: npm run build:storybook
      - name: Deploy Dev Storybook to Netlify
        if: github.event.pull_request.base.ref == 'v2/dev'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          production-branch: v2/main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: storybook-preview-v2-dev-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy Main Storybook to Netlify
        if: github.event.pull_request.base.ref == 'v2/main'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          production-branch: v2/main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: storybook-preview-v2-main-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
