name: Publish Next Patch (react-18)
on:
  push:
    branches:
      - chore/react-18-upgrade
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Update NPM version
        run: npm install -g "npm@^10.8.2"
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Test
        run: npm test
      - name: Coverage
        uses: codecov/codecov-action@v1
      - name: Build Docs
        run: npm run build:docs
      - name: Build Storybook
        run: npm run build:storybook
      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy React 18 from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: react-18
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy Dev Storybook to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: storybook-preview-react-18
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
