name: Build and Publish Docs for old versions

on:
  push:
    branches:
      - chore/deployOldDocs

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['4.3.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: react-magma-dom@${{ matrix.version }}
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Patch Missing _styled Export
        run: |
          # Path to the problematic file
          FILE_PATH="packages/react-magma-dom/dist/esm/index.js"

          if [ -f "$FILE_PATH" ]; then
            echo "Found file $FILE_PATH, applying patch..."

            # Make a backup
            cp "$FILE_PATH" "$FILE_PATH.bak"

            # Create a temporary file containing the new content
            # First add the import, then include original content
            echo "import styled from '@emotion/styled';" > temp_file
            echo "const _styled = styled;" >> temp_file
            cat "$FILE_PATH" >> temp_file

            # Replace original file with the patched version
            mv temp_file "$FILE_PATH"

            echo "File patched successfully"
          else
            echo "File $FILE_PATH not found"
          fi

      - name: Configure NPM
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc

      - name: Get Alias
        id: info
        run: |
          echo "::set-output name=alias::$(npm run --silent getAlias)"
          echo "::set-output name=version::$(npm run --silent getVersion)"

      - name: Build Docs
        run: npm run build:docs
        env:
          PATH_PREFIX: /version/${{ matrix.version }}

      - name: Deploy Docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ matrix.version }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
