// Generated from packages/design-tokens. Do not edit by hand.
export interface TokenDefinition {
  alias?: string;
  cssValue?: string;
  legacyPath: string;
  sourcePath: string;
  type: string;
}

export const TOKEN_DEFINITIONS: {
  [path: string]: TokenDefinition;
} = {
  'colors.primary100': {
    cssValue: '#E8E9F8',
    legacyPath: 'colors.primary100',
    sourcePath: 'color.primary.100',
    type: 'color',
  },
  'colors.primary200': {
    cssValue: '#BABDE9',
    legacyPath: 'colors.primary200',
    sourcePath: 'color.primary.200',
    type: 'color',
  },
  'colors.primary300': {
    cssValue: '#8B91DA',
    legacyPath: 'colors.primary300',
    sourcePath: 'color.primary.300',
    type: 'color',
  },
  'colors.primary400': {
    cssValue: '#5D65CB',
    legacyPath: 'colors.primary400',
    sourcePath: 'color.primary.400',
    type: 'color',
  },
  'colors.primary500': {
    cssValue: '#3942B0',
    legacyPath: 'colors.primary500',
    sourcePath: 'color.primary.500',
    type: 'color',
  },
  'colors.primary600': {
    cssValue: '#292F7C',
    legacyPath: 'colors.primary600',
    sourcePath: 'color.primary.600',
    type: 'color',
  },
  'colors.primary700': {
    cssValue: '#1A1E51',
    legacyPath: 'colors.primary700',
    sourcePath: 'color.primary.700',
    type: 'color',
  },
  'colors.primary': {
    alias: 'colors.primary500',
    legacyPath: 'colors.primary',
    sourcePath: 'color.primary.default',
    type: 'color',
  },
  'colors.secondary500': {
    cssValue: '#FEE449',
    legacyPath: 'colors.secondary500',
    sourcePath: 'color.secondary.500',
    type: 'color',
  },
  'colors.secondary600': {
    cssValue: '#FEDA0D',
    legacyPath: 'colors.secondary600',
    sourcePath: 'color.secondary.600',
    type: 'color',
  },
  'colors.secondary700': {
    cssValue: '#ECC901',
    legacyPath: 'colors.secondary700',
    sourcePath: 'color.secondary.700',
    type: 'color',
  },
  'colors.secondary': {
    alias: 'colors.secondary500',
    legacyPath: 'colors.secondary',
    sourcePath: 'color.secondary.default',
    type: 'color',
  },
  'colors.tertiary500': {
    cssValue: '#CDDEFF',
    legacyPath: 'colors.tertiary500',
    sourcePath: 'color.tertiary.500',
    type: 'color',
  },
  'colors.tertiary600': {
    cssValue: '#A2C1FF',
    legacyPath: 'colors.tertiary600',
    sourcePath: 'color.tertiary.600',
    type: 'color',
  },
  'colors.tertiary700': {
    cssValue: '#79A5FF',
    legacyPath: 'colors.tertiary700',
    sourcePath: 'color.tertiary.700',
    type: 'color',
  },
  'colors.tertiary': {
    alias: 'colors.tertiary500',
    legacyPath: 'colors.tertiary',
    sourcePath: 'color.tertiary.default',
    type: 'color',
  },
  'colors.neutral100': {
    cssValue: '#FFFFFF',
    legacyPath: 'colors.neutral100',
    sourcePath: 'color.neutral.100',
    type: 'color',
  },
  'colors.neutral200': {
    cssValue: '#F5F5F5',
    legacyPath: 'colors.neutral200',
    sourcePath: 'color.neutral.200',
    type: 'color',
  },
  'colors.neutral300': {
    cssValue: '#D4D4D4',
    legacyPath: 'colors.neutral300',
    sourcePath: 'color.neutral.300',
    type: 'color',
  },
  'colors.neutral400': {
    cssValue: '#8D8D8D',
    legacyPath: 'colors.neutral400',
    sourcePath: 'color.neutral.400',
    type: 'color',
  },
  'colors.neutral500': {
    cssValue: '#707070',
    legacyPath: 'colors.neutral500',
    sourcePath: 'color.neutral.500',
    type: 'color',
  },
  'colors.neutral600': {
    cssValue: '#5A5A5A',
    legacyPath: 'colors.neutral600',
    sourcePath: 'color.neutral.600',
    type: 'color',
  },
  'colors.neutral700': {
    cssValue: '#454545',
    legacyPath: 'colors.neutral700',
    sourcePath: 'color.neutral.700',
    type: 'color',
  },
  'colors.neutral800': {
    cssValue: '#2D2D2D',
    legacyPath: 'colors.neutral800',
    sourcePath: 'color.neutral.800',
    type: 'color',
  },
  'colors.neutral900': {
    cssValue: '#000000',
    legacyPath: 'colors.neutral900',
    sourcePath: 'color.neutral.900',
    type: 'color',
  },
  'colors.neutral': {
    alias: 'colors.neutral500',
    legacyPath: 'colors.neutral',
    sourcePath: 'color.neutral.default',
    type: 'color',
  },
  'colors.info100': {
    cssValue: '#E8F5FC',
    legacyPath: 'colors.info100',
    sourcePath: 'color.info.100',
    type: 'color',
  },
  'colors.info200': {
    cssValue: '#A6DEFF',
    legacyPath: 'colors.info200',
    sourcePath: 'color.info.200',
    type: 'color',
  },
  'colors.info300': {
    cssValue: '#2FB3FF',
    legacyPath: 'colors.info300',
    sourcePath: 'color.info.300',
    type: 'color',
  },
  'colors.info400': {
    cssValue: '#009AF3',
    legacyPath: 'colors.info400',
    sourcePath: 'color.info.400',
    type: 'color',
  },
  'colors.info500': {
    cssValue: '#0074B7',
    legacyPath: 'colors.info500',
    sourcePath: 'color.info.500',
    type: 'color',
  },
  'colors.info600': {
    cssValue: '#005F96',
    legacyPath: 'colors.info600',
    sourcePath: 'color.info.600',
    type: 'color',
  },
  'colors.info700': {
    cssValue: '#004A75',
    legacyPath: 'colors.info700',
    sourcePath: 'color.info.700',
    type: 'color',
  },
  'colors.info': {
    alias: 'colors.info500',
    legacyPath: 'colors.info',
    sourcePath: 'color.info.default',
    type: 'color',
  },
  'colors.danger100': {
    cssValue: '#FDEFEE',
    legacyPath: 'colors.danger100',
    sourcePath: 'color.danger.100',
    type: 'color',
  },
  'colors.danger200': {
    cssValue: '#FAAEB0',
    legacyPath: 'colors.danger200',
    sourcePath: 'color.danger.200',
    type: 'color',
  },
  'colors.danger300': {
    cssValue: '#E8716D',
    legacyPath: 'colors.danger300',
    sourcePath: 'color.danger.300',
    type: 'color',
  },
  'colors.danger400': {
    cssValue: '#E24943',
    legacyPath: 'colors.danger400',
    sourcePath: 'color.danger.400',
    type: 'color',
  },
  'colors.danger500': {
    cssValue: '#D32821',
    legacyPath: 'colors.danger500',
    sourcePath: 'color.danger.500',
    type: 'color',
  },
  'colors.danger600': {
    cssValue: '#A91F1A',
    legacyPath: 'colors.danger600',
    sourcePath: 'color.danger.600',
    type: 'color',
  },
  'colors.danger700': {
    cssValue: '#7F1714',
    legacyPath: 'colors.danger700',
    sourcePath: 'color.danger.700',
    type: 'color',
  },
  'colors.danger': {
    alias: 'colors.danger500',
    legacyPath: 'colors.danger',
    sourcePath: 'color.danger.default',
    type: 'color',
  },
  'colors.warning100': {
    cssValue: '#FCEEE5',
    legacyPath: 'colors.warning100',
    sourcePath: 'color.warning.100',
    type: 'color',
  },
  'colors.warning200': {
    cssValue: '#F6CDB2',
    legacyPath: 'colors.warning200',
    sourcePath: 'color.warning.200',
    type: 'color',
  },
  'colors.warning300': {
    cssValue: '#E98B4C',
    legacyPath: 'colors.warning300',
    sourcePath: 'color.warning.300',
    type: 'color',
  },
  'colors.warning400': {
    cssValue: '#E06A1C',
    legacyPath: 'colors.warning400',
    sourcePath: 'color.warning.400',
    type: 'color',
  },
  'colors.warning500': {
    cssValue: '#AD5115',
    legacyPath: 'colors.warning500',
    sourcePath: 'color.warning.500',
    type: 'color',
  },
  'colors.warning600': {
    cssValue: '#8D4311',
    legacyPath: 'colors.warning600',
    sourcePath: 'color.warning.600',
    type: 'color',
  },
  'colors.warning700': {
    cssValue: '#6E340E',
    legacyPath: 'colors.warning700',
    sourcePath: 'color.warning.700',
    type: 'color',
  },
  'colors.warning': {
    alias: 'colors.warning500',
    legacyPath: 'colors.warning',
    sourcePath: 'color.warning.default',
    type: 'color',
  },
  'colors.success100': {
    cssValue: '#E3FAEA',
    legacyPath: 'colors.success100',
    sourcePath: 'color.success.100',
    type: 'color',
  },
  'colors.success200': {
    cssValue: '#ACF0C1',
    legacyPath: 'colors.success200',
    sourcePath: 'color.success.200',
    type: 'color',
  },
  'colors.success300': {
    cssValue: '#3EDD6E',
    legacyPath: 'colors.success300',
    sourcePath: 'color.success.300',
    type: 'color',
  },
  'colors.success400': {
    cssValue: '#21B94E',
    legacyPath: 'colors.success400',
    sourcePath: 'color.success.400',
    type: 'color',
  },
  'colors.success500': {
    cssValue: '#178037',
    legacyPath: 'colors.success500',
    sourcePath: 'color.success.500',
    type: 'color',
  },
  'colors.success600': {
    cssValue: '#136A2D',
    legacyPath: 'colors.success600',
    sourcePath: 'color.success.600',
    type: 'color',
  },
  'colors.success700': {
    cssValue: '#0F5323',
    legacyPath: 'colors.success700',
    sourcePath: 'color.success.700',
    type: 'color',
  },
  'colors.success': {
    alias: 'colors.success500',
    legacyPath: 'colors.success',
    sourcePath: 'color.success.default',
    type: 'color',
  },
  'colors.focus': {
    alias: 'colors.info500',
    legacyPath: 'colors.focus',
    sourcePath: 'color.focus',
    type: 'color',
  },
  'colors.focusInverse': {
    alias: 'colors.info200',
    legacyPath: 'colors.focusInverse',
    sourcePath: 'color.focusInverse',
    type: 'color',
  },
  'colors.border': {
    alias: 'colors.neutral300',
    legacyPath: 'colors.border',
    sourcePath: 'color.border',
    type: 'color',
  },
  'colors.borderInverse': {
    cssValue: 'rgba(255, 255, 255, 0.25)',
    legacyPath: 'colors.borderInverse',
    sourcePath: 'color.borderInverse',
    type: 'color',
  },
  'spaceScale.spacing10': {
    cssValue: '48px',
    legacyPath: 'spaceScale.spacing10',
    sourcePath: 'space.10',
    type: 'dimension',
  },
  'spaceScale.spacing11': {
    cssValue: '56px',
    legacyPath: 'spaceScale.spacing11',
    sourcePath: 'space.11',
    type: 'dimension',
  },
  'spaceScale.spacing12': {
    cssValue: '64px',
    legacyPath: 'spaceScale.spacing12',
    sourcePath: 'space.12',
    type: 'dimension',
  },
  'spaceScale.spacing13': {
    cssValue: '96px',
    legacyPath: 'spaceScale.spacing13',
    sourcePath: 'space.13',
    type: 'dimension',
  },
  'spaceScale.spacing14': {
    cssValue: '160px',
    legacyPath: 'spaceScale.spacing14',
    sourcePath: 'space.14',
    type: 'dimension',
  },
  'spaceScale.spacing01': {
    cssValue: '2px',
    legacyPath: 'spaceScale.spacing01',
    sourcePath: 'space.01',
    type: 'dimension',
  },
  'spaceScale.spacing02': {
    cssValue: '4px',
    legacyPath: 'spaceScale.spacing02',
    sourcePath: 'space.02',
    type: 'dimension',
  },
  'spaceScale.spacing03': {
    cssValue: '8px',
    legacyPath: 'spaceScale.spacing03',
    sourcePath: 'space.03',
    type: 'dimension',
  },
  'spaceScale.spacing04': {
    cssValue: '12px',
    legacyPath: 'spaceScale.spacing04',
    sourcePath: 'space.04',
    type: 'dimension',
  },
  'spaceScale.spacing05': {
    cssValue: '16px',
    legacyPath: 'spaceScale.spacing05',
    sourcePath: 'space.05',
    type: 'dimension',
  },
  'spaceScale.spacing06': {
    cssValue: '24px',
    legacyPath: 'spaceScale.spacing06',
    sourcePath: 'space.06',
    type: 'dimension',
  },
  'spaceScale.spacing07': {
    cssValue: '28px',
    legacyPath: 'spaceScale.spacing07',
    sourcePath: 'space.07',
    type: 'dimension',
  },
  'spaceScale.spacing08': {
    cssValue: '32px',
    legacyPath: 'spaceScale.spacing08',
    sourcePath: 'space.08',
    type: 'dimension',
  },
  'spaceScale.spacing09': {
    cssValue: '40px',
    legacyPath: 'spaceScale.spacing09',
    sourcePath: 'space.09',
    type: 'dimension',
  },
  borderRadius: {
    cssValue: '8px',
    legacyPath: 'borderRadius',
    sourcePath: 'radius.default',
    type: 'dimension',
  },
  borderRadiusSmall: {
    cssValue: '4px',
    legacyPath: 'borderRadiusSmall',
    sourcePath: 'radius.small',
    type: 'dimension',
  },
  bodyFont: {
    cssValue: '"Work Sans", Helvetica, sans-serif',
    legacyPath: 'bodyFont',
    sourcePath: 'font.body',
    type: 'fontFamily',
  },
  bodyExpressiveFont: {
    cssValue: '"Work Sans", Helvetica, sans-serif',
    legacyPath: 'bodyExpressiveFont',
    sourcePath: 'font.bodyExpressive',
    type: 'fontFamily',
  },
  bodyNarrativeFont: {
    cssValue: '"Noto Serif", "Times New Roman", serif',
    legacyPath: 'bodyNarrativeFont',
    sourcePath: 'font.bodyNarrative',
    type: 'fontFamily',
  },
  headingFont: {
    cssValue: '"Work Sans", Helvetica, sans-serif',
    legacyPath: 'headingFont',
    sourcePath: 'font.heading',
    type: 'fontFamily',
  },
  headingExpressiveFont: {
    cssValue: '"Work Sans", Helvetica, sans-serif',
    legacyPath: 'headingExpressiveFont',
    sourcePath: 'font.headingExpressive',
    type: 'fontFamily',
  },
  headingNarrativeFont: {
    cssValue: '"Noto Serif", "Times New Roman", serif',
    legacyPath: 'headingNarrativeFont',
    sourcePath: 'font.headingNarrative',
    type: 'fontFamily',
  },
  'typeScale.size01.fontSize': {
    cssValue: '12px',
    legacyPath: 'typeScale.size01.fontSize',
    sourcePath: 'typeScale.size01.fontSize',
    type: 'dimension',
  },
  'typeScale.size01.letterSpacing': {
    cssValue: '0.32px',
    legacyPath: 'typeScale.size01.letterSpacing',
    sourcePath: 'typeScale.size01.letterSpacing',
    type: 'dimension',
  },
  'typeScale.size01.lineHeight': {
    cssValue: '16px',
    legacyPath: 'typeScale.size01.lineHeight',
    sourcePath: 'typeScale.size01.lineHeight',
    type: 'dimension',
  },
  'typeScale.size02.fontSize': {
    cssValue: '14px',
    legacyPath: 'typeScale.size02.fontSize',
    sourcePath: 'typeScale.size02.fontSize',
    type: 'dimension',
  },
  'typeScale.size02.letterSpacing': {
    cssValue: '0.16px',
    legacyPath: 'typeScale.size02.letterSpacing',
    sourcePath: 'typeScale.size02.letterSpacing',
    type: 'dimension',
  },
  'typeScale.size02.lineHeight': {
    cssValue: '20px',
    legacyPath: 'typeScale.size02.lineHeight',
    sourcePath: 'typeScale.size02.lineHeight',
    type: 'dimension',
  },
  'typeScale.size03.fontSize': {
    cssValue: '16px',
    legacyPath: 'typeScale.size03.fontSize',
    sourcePath: 'typeScale.size03.fontSize',
    type: 'dimension',
  },
  'typeScale.size03.letterSpacing': {
    cssValue: '0.32px',
    legacyPath: 'typeScale.size03.letterSpacing',
    sourcePath: 'typeScale.size03.letterSpacing',
    type: 'dimension',
  },
  'typeScale.size03.lineHeight': {
    cssValue: '24px',
    legacyPath: 'typeScale.size03.lineHeight',
    sourcePath: 'typeScale.size03.lineHeight',
    type: 'dimension',
  },
  'typeScale.size04.fontSize': {
    cssValue: '18px',
    legacyPath: 'typeScale.size04.fontSize',
    sourcePath: 'typeScale.size04.fontSize',
    type: 'dimension',
  },
  'typeScale.size04.lineHeight': {
    cssValue: '24px',
    legacyPath: 'typeScale.size04.lineHeight',
    sourcePath: 'typeScale.size04.lineHeight',
    type: 'dimension',
  },
  'semanticColors.focus.default': {
    alias: 'colors.focus',
    legacyPath: 'semanticColors.focus.default',
    sourcePath: 'semanticColors.focus.default',
    type: 'color',
  },
  'semanticColors.focus.inverse': {
    alias: 'colors.focusInverse',
    legacyPath: 'semanticColors.focus.inverse',
    sourcePath: 'semanticColors.focus.inverse',
    type: 'color',
  },
  'semanticColors.surface.default': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.surface.default',
    sourcePath: 'semanticColors.surface.default',
    type: 'color',
  },
  'semanticColors.surface.inverse': {
    alias: 'colors.primary600',
    legacyPath: 'semanticColors.surface.inverse',
    sourcePath: 'semanticColors.surface.inverse',
    type: 'color',
  },
  'semanticColors.surface.subtle': {
    alias: 'colors.neutral200',
    legacyPath: 'semanticColors.surface.subtle',
    sourcePath: 'semanticColors.surface.subtle',
    type: 'color',
  },
  'semanticColors.text.default': {
    alias: 'colors.neutral',
    legacyPath: 'semanticColors.text.default',
    sourcePath: 'semanticColors.text.default',
    type: 'color',
  },
  'semanticColors.text.inverse': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.text.inverse',
    sourcePath: 'semanticColors.text.inverse',
    type: 'color',
  },
  'semanticColors.text.link': {
    alias: 'colors.primary',
    legacyPath: 'semanticColors.text.link',
    sourcePath: 'semanticColors.text.link',
    type: 'color',
  },
  'semanticColors.text.linkHover': {
    alias: 'colors.primary700',
    legacyPath: 'semanticColors.text.linkHover',
    sourcePath: 'semanticColors.text.linkHover',
    type: 'color',
  },
  'semanticColors.text.inverseLink': {
    alias: 'colors.tertiary',
    legacyPath: 'semanticColors.text.inverseLink',
    sourcePath: 'semanticColors.text.inverseLink',
    type: 'color',
  },
  'semanticColors.text.inverseLinkHover': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.text.inverseLinkHover',
    sourcePath: 'semanticColors.text.inverseLinkHover',
    type: 'color',
  },
  'semanticColors.status.danger.border': {
    alias: 'colors.danger500',
    legacyPath: 'semanticColors.status.danger.border',
    sourcePath: 'semanticColors.status.danger.border',
    type: 'color',
  },
  'semanticColors.status.danger.icon': {
    alias: 'colors.danger500',
    legacyPath: 'semanticColors.status.danger.icon',
    sourcePath: 'semanticColors.status.danger.icon',
    type: 'color',
  },
  'semanticColors.status.danger.inverseBorder': {
    alias: 'colors.danger200',
    legacyPath: 'semanticColors.status.danger.inverseBorder',
    sourcePath: 'semanticColors.status.danger.inverseBorder',
    type: 'color',
  },
  'semanticColors.status.danger.inverseIcon': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.status.danger.inverseIcon',
    sourcePath: 'semanticColors.status.danger.inverseIcon',
    type: 'color',
  },
  'semanticColors.status.danger.inverseLink': {
    alias: 'colors.danger200',
    legacyPath: 'semanticColors.status.danger.inverseLink',
    sourcePath: 'semanticColors.status.danger.inverseLink',
    type: 'color',
  },
  'semanticColors.status.danger.inverseSurface': {
    alias: 'colors.danger700',
    legacyPath: 'semanticColors.status.danger.inverseSurface',
    sourcePath: 'semanticColors.status.danger.inverseSurface',
    type: 'color',
  },
  'semanticColors.status.danger.link': {
    alias: 'colors.danger700',
    legacyPath: 'semanticColors.status.danger.link',
    sourcePath: 'semanticColors.status.danger.link',
    type: 'color',
  },
  'semanticColors.status.danger.linkHover': {
    alias: 'colors.danger',
    legacyPath: 'semanticColors.status.danger.linkHover',
    sourcePath: 'semanticColors.status.danger.linkHover',
    type: 'color',
  },
  'semanticColors.status.danger.surface': {
    alias: 'colors.danger100',
    legacyPath: 'semanticColors.status.danger.surface',
    sourcePath: 'semanticColors.status.danger.surface',
    type: 'color',
  },
  'semanticColors.status.danger.text': {
    alias: 'colors.danger500',
    legacyPath: 'semanticColors.status.danger.text',
    sourcePath: 'semanticColors.status.danger.text',
    type: 'color',
  },
  'semanticColors.status.info.border': {
    alias: 'colors.info500',
    legacyPath: 'semanticColors.status.info.border',
    sourcePath: 'semanticColors.status.info.border',
    type: 'color',
  },
  'semanticColors.status.info.icon': {
    alias: 'colors.info500',
    legacyPath: 'semanticColors.status.info.icon',
    sourcePath: 'semanticColors.status.info.icon',
    type: 'color',
  },
  'semanticColors.status.info.inverseBorder': {
    alias: 'colors.info300',
    legacyPath: 'semanticColors.status.info.inverseBorder',
    sourcePath: 'semanticColors.status.info.inverseBorder',
    type: 'color',
  },
  'semanticColors.status.info.inverseIcon': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.status.info.inverseIcon',
    sourcePath: 'semanticColors.status.info.inverseIcon',
    type: 'color',
  },
  'semanticColors.status.info.inverseLink': {
    alias: 'colors.info200',
    legacyPath: 'semanticColors.status.info.inverseLink',
    sourcePath: 'semanticColors.status.info.inverseLink',
    type: 'color',
  },
  'semanticColors.status.info.inverseSurface': {
    alias: 'colors.info700',
    legacyPath: 'semanticColors.status.info.inverseSurface',
    sourcePath: 'semanticColors.status.info.inverseSurface',
    type: 'color',
  },
  'semanticColors.status.info.link': {
    alias: 'colors.info700',
    legacyPath: 'semanticColors.status.info.link',
    sourcePath: 'semanticColors.status.info.link',
    type: 'color',
  },
  'semanticColors.status.info.linkHover': {
    alias: 'colors.info',
    legacyPath: 'semanticColors.status.info.linkHover',
    sourcePath: 'semanticColors.status.info.linkHover',
    type: 'color',
  },
  'semanticColors.status.info.surface': {
    alias: 'colors.info100',
    legacyPath: 'semanticColors.status.info.surface',
    sourcePath: 'semanticColors.status.info.surface',
    type: 'color',
  },
  'semanticColors.status.info.text': {
    alias: 'colors.info500',
    legacyPath: 'semanticColors.status.info.text',
    sourcePath: 'semanticColors.status.info.text',
    type: 'color',
  },
  'semanticColors.status.success.border': {
    alias: 'colors.success500',
    legacyPath: 'semanticColors.status.success.border',
    sourcePath: 'semanticColors.status.success.border',
    type: 'color',
  },
  'semanticColors.status.success.icon': {
    alias: 'colors.success500',
    legacyPath: 'semanticColors.status.success.icon',
    sourcePath: 'semanticColors.status.success.icon',
    type: 'color',
  },
  'semanticColors.status.success.inverseBorder': {
    alias: 'colors.success300',
    legacyPath: 'semanticColors.status.success.inverseBorder',
    sourcePath: 'semanticColors.status.success.inverseBorder',
    type: 'color',
  },
  'semanticColors.status.success.inverseIcon': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.status.success.inverseIcon',
    sourcePath: 'semanticColors.status.success.inverseIcon',
    type: 'color',
  },
  'semanticColors.status.success.inverseLink': {
    alias: 'colors.success200',
    legacyPath: 'semanticColors.status.success.inverseLink',
    sourcePath: 'semanticColors.status.success.inverseLink',
    type: 'color',
  },
  'semanticColors.status.success.inverseSurface': {
    alias: 'colors.success700',
    legacyPath: 'semanticColors.status.success.inverseSurface',
    sourcePath: 'semanticColors.status.success.inverseSurface',
    type: 'color',
  },
  'semanticColors.status.success.link': {
    alias: 'colors.success700',
    legacyPath: 'semanticColors.status.success.link',
    sourcePath: 'semanticColors.status.success.link',
    type: 'color',
  },
  'semanticColors.status.success.linkHover': {
    alias: 'colors.success',
    legacyPath: 'semanticColors.status.success.linkHover',
    sourcePath: 'semanticColors.status.success.linkHover',
    type: 'color',
  },
  'semanticColors.status.success.surface': {
    alias: 'colors.success100',
    legacyPath: 'semanticColors.status.success.surface',
    sourcePath: 'semanticColors.status.success.surface',
    type: 'color',
  },
  'semanticColors.status.success.text': {
    alias: 'colors.success500',
    legacyPath: 'semanticColors.status.success.text',
    sourcePath: 'semanticColors.status.success.text',
    type: 'color',
  },
  'semanticColors.status.warning.border': {
    alias: 'colors.warning500',
    legacyPath: 'semanticColors.status.warning.border',
    sourcePath: 'semanticColors.status.warning.border',
    type: 'color',
  },
  'semanticColors.status.warning.icon': {
    alias: 'colors.warning500',
    legacyPath: 'semanticColors.status.warning.icon',
    sourcePath: 'semanticColors.status.warning.icon',
    type: 'color',
  },
  'semanticColors.status.warning.inverseBorder': {
    alias: 'colors.warning300',
    legacyPath: 'semanticColors.status.warning.inverseBorder',
    sourcePath: 'semanticColors.status.warning.inverseBorder',
    type: 'color',
  },
  'semanticColors.status.warning.inverseIcon': {
    alias: 'colors.neutral100',
    legacyPath: 'semanticColors.status.warning.inverseIcon',
    sourcePath: 'semanticColors.status.warning.inverseIcon',
    type: 'color',
  },
  'semanticColors.status.warning.inverseLink': {
    alias: 'colors.warning200',
    legacyPath: 'semanticColors.status.warning.inverseLink',
    sourcePath: 'semanticColors.status.warning.inverseLink',
    type: 'color',
  },
  'semanticColors.status.warning.inverseSurface': {
    alias: 'colors.warning700',
    legacyPath: 'semanticColors.status.warning.inverseSurface',
    sourcePath: 'semanticColors.status.warning.inverseSurface',
    type: 'color',
  },
  'semanticColors.status.warning.link': {
    alias: 'colors.warning700',
    legacyPath: 'semanticColors.status.warning.link',
    sourcePath: 'semanticColors.status.warning.link',
    type: 'color',
  },
  'semanticColors.status.warning.linkHover': {
    alias: 'colors.warning',
    legacyPath: 'semanticColors.status.warning.linkHover',
    sourcePath: 'semanticColors.status.warning.linkHover',
    type: 'color',
  },
  'semanticColors.status.warning.surface': {
    alias: 'colors.warning100',
    legacyPath: 'semanticColors.status.warning.surface',
    sourcePath: 'semanticColors.status.warning.surface',
    type: 'color',
  },
  'semanticColors.status.warning.text': {
    alias: 'colors.warning500',
    legacyPath: 'semanticColors.status.warning.text',
    sourcePath: 'semanticColors.status.warning.text',
    type: 'color',
  },
  'components.alert.info.background': {
    alias: 'semanticColors.status.info.surface',
    legacyPath: 'components.alert.info.background',
    sourcePath: 'components.alert.info.background',
    type: 'color',
  },
  'components.alert.info.border': {
    alias: 'semanticColors.status.info.border',
    legacyPath: 'components.alert.info.border',
    sourcePath: 'components.alert.info.border',
    type: 'color',
  },
  'components.alert.info.icon': {
    alias: 'semanticColors.status.info.icon',
    legacyPath: 'components.alert.info.icon',
    sourcePath: 'components.alert.info.icon',
    type: 'color',
  },
  'components.alert.info.link': {
    alias: 'semanticColors.status.info.link',
    legacyPath: 'components.alert.info.link',
    sourcePath: 'components.alert.info.link',
    type: 'color',
  },
  'components.alert.info.linkHover': {
    alias: 'semanticColors.status.info.linkHover',
    legacyPath: 'components.alert.info.linkHover',
    sourcePath: 'components.alert.info.linkHover',
    type: 'color',
  },
  'components.alert.info.inverse.background': {
    alias: 'semanticColors.status.info.inverseSurface',
    legacyPath: 'components.alert.info.inverse.background',
    sourcePath: 'components.alert.info.inverse.background',
    type: 'color',
  },
  'components.alert.info.inverse.border': {
    alias: 'semanticColors.status.info.inverseBorder',
    legacyPath: 'components.alert.info.inverse.border',
    sourcePath: 'components.alert.info.inverse.border',
    type: 'color',
  },
  'components.alert.info.inverse.icon': {
    alias: 'semanticColors.status.info.inverseIcon',
    legacyPath: 'components.alert.info.inverse.icon',
    sourcePath: 'components.alert.info.inverse.icon',
    type: 'color',
  },
  'components.alert.info.inverse.link': {
    alias: 'semanticColors.status.info.inverseLink',
    legacyPath: 'components.alert.info.inverse.link',
    sourcePath: 'components.alert.info.inverse.link',
    type: 'color',
  },
  'components.alert.info.inverse.linkHover': {
    alias: 'semanticColors.text.inverse',
    legacyPath: 'components.alert.info.inverse.linkHover',
    sourcePath: 'components.alert.info.inverse.linkHover',
    type: 'color',
  },
  'components.alert.success.background': {
    alias: 'semanticColors.status.success.surface',
    legacyPath: 'components.alert.success.background',
    sourcePath: 'components.alert.success.background',
    type: 'color',
  },
  'components.alert.success.border': {
    alias: 'semanticColors.status.success.border',
    legacyPath: 'components.alert.success.border',
    sourcePath: 'components.alert.success.border',
    type: 'color',
  },
  'components.alert.success.icon': {
    alias: 'semanticColors.status.success.icon',
    legacyPath: 'components.alert.success.icon',
    sourcePath: 'components.alert.success.icon',
    type: 'color',
  },
  'components.alert.success.link': {
    alias: 'semanticColors.status.success.link',
    legacyPath: 'components.alert.success.link',
    sourcePath: 'components.alert.success.link',
    type: 'color',
  },
  'components.alert.success.linkHover': {
    alias: 'semanticColors.status.success.linkHover',
    legacyPath: 'components.alert.success.linkHover',
    sourcePath: 'components.alert.success.linkHover',
    type: 'color',
  },
  'components.alert.success.inverse.background': {
    alias: 'semanticColors.status.success.inverseSurface',
    legacyPath: 'components.alert.success.inverse.background',
    sourcePath: 'components.alert.success.inverse.background',
    type: 'color',
  },
  'components.alert.success.inverse.border': {
    alias: 'semanticColors.status.success.inverseBorder',
    legacyPath: 'components.alert.success.inverse.border',
    sourcePath: 'components.alert.success.inverse.border',
    type: 'color',
  },
  'components.alert.success.inverse.icon': {
    alias: 'semanticColors.status.success.inverseIcon',
    legacyPath: 'components.alert.success.inverse.icon',
    sourcePath: 'components.alert.success.inverse.icon',
    type: 'color',
  },
  'components.alert.success.inverse.link': {
    alias: 'semanticColors.status.success.inverseLink',
    legacyPath: 'components.alert.success.inverse.link',
    sourcePath: 'components.alert.success.inverse.link',
    type: 'color',
  },
  'components.alert.success.inverse.linkHover': {
    alias: 'semanticColors.text.inverse',
    legacyPath: 'components.alert.success.inverse.linkHover',
    sourcePath: 'components.alert.success.inverse.linkHover',
    type: 'color',
  },
  'components.alert.warning.background': {
    alias: 'semanticColors.status.warning.surface',
    legacyPath: 'components.alert.warning.background',
    sourcePath: 'components.alert.warning.background',
    type: 'color',
  },
  'components.alert.warning.border': {
    alias: 'semanticColors.status.warning.border',
    legacyPath: 'components.alert.warning.border',
    sourcePath: 'components.alert.warning.border',
    type: 'color',
  },
  'components.alert.warning.icon': {
    alias: 'semanticColors.status.warning.icon',
    legacyPath: 'components.alert.warning.icon',
    sourcePath: 'components.alert.warning.icon',
    type: 'color',
  },
  'components.alert.warning.link': {
    alias: 'semanticColors.status.warning.link',
    legacyPath: 'components.alert.warning.link',
    sourcePath: 'components.alert.warning.link',
    type: 'color',
  },
  'components.alert.warning.linkHover': {
    alias: 'semanticColors.status.warning.linkHover',
    legacyPath: 'components.alert.warning.linkHover',
    sourcePath: 'components.alert.warning.linkHover',
    type: 'color',
  },
  'components.alert.warning.inverse.background': {
    alias: 'semanticColors.status.warning.inverseSurface',
    legacyPath: 'components.alert.warning.inverse.background',
    sourcePath: 'components.alert.warning.inverse.background',
    type: 'color',
  },
  'components.alert.warning.inverse.border': {
    alias: 'semanticColors.status.warning.inverseBorder',
    legacyPath: 'components.alert.warning.inverse.border',
    sourcePath: 'components.alert.warning.inverse.border',
    type: 'color',
  },
  'components.alert.warning.inverse.icon': {
    alias: 'semanticColors.status.warning.inverseIcon',
    legacyPath: 'components.alert.warning.inverse.icon',
    sourcePath: 'components.alert.warning.inverse.icon',
    type: 'color',
  },
  'components.alert.warning.inverse.link': {
    alias: 'semanticColors.status.warning.inverseLink',
    legacyPath: 'components.alert.warning.inverse.link',
    sourcePath: 'components.alert.warning.inverse.link',
    type: 'color',
  },
  'components.alert.warning.inverse.linkHover': {
    alias: 'semanticColors.text.inverse',
    legacyPath: 'components.alert.warning.inverse.linkHover',
    sourcePath: 'components.alert.warning.inverse.linkHover',
    type: 'color',
  },
  'components.alert.danger.background': {
    alias: 'semanticColors.status.danger.surface',
    legacyPath: 'components.alert.danger.background',
    sourcePath: 'components.alert.danger.background',
    type: 'color',
  },
  'components.alert.danger.border': {
    alias: 'semanticColors.status.danger.border',
    legacyPath: 'components.alert.danger.border',
    sourcePath: 'components.alert.danger.border',
    type: 'color',
  },
  'components.alert.danger.icon': {
    alias: 'semanticColors.status.danger.icon',
    legacyPath: 'components.alert.danger.icon',
    sourcePath: 'components.alert.danger.icon',
    type: 'color',
  },
  'components.alert.danger.link': {
    alias: 'semanticColors.status.danger.link',
    legacyPath: 'components.alert.danger.link',
    sourcePath: 'components.alert.danger.link',
    type: 'color',
  },
  'components.alert.danger.linkHover': {
    alias: 'semanticColors.status.danger.linkHover',
    legacyPath: 'components.alert.danger.linkHover',
    sourcePath: 'components.alert.danger.linkHover',
    type: 'color',
  },
  'components.alert.danger.inverse.background': {
    alias: 'semanticColors.status.danger.inverseSurface',
    legacyPath: 'components.alert.danger.inverse.background',
    sourcePath: 'components.alert.danger.inverse.background',
    type: 'color',
  },
  'components.alert.danger.inverse.border': {
    alias: 'semanticColors.status.danger.inverseBorder',
    legacyPath: 'components.alert.danger.inverse.border',
    sourcePath: 'components.alert.danger.inverse.border',
    type: 'color',
  },
  'components.alert.danger.inverse.icon': {
    alias: 'semanticColors.status.danger.inverseIcon',
    legacyPath: 'components.alert.danger.inverse.icon',
    sourcePath: 'components.alert.danger.inverse.icon',
    type: 'color',
  },
  'components.alert.danger.inverse.link': {
    alias: 'semanticColors.status.danger.inverseLink',
    legacyPath: 'components.alert.danger.inverse.link',
    sourcePath: 'components.alert.danger.inverse.link',
    type: 'color',
  },
  'components.alert.danger.inverse.linkHover': {
    alias: 'semanticColors.text.inverse',
    legacyPath: 'components.alert.danger.inverse.linkHover',
    sourcePath: 'components.alert.danger.inverse.linkHover',
    type: 'color',
  },
  'components.button.fontFamily': {
    alias: 'bodyFont',
    legacyPath: 'components.button.fontFamily',
    sourcePath: 'components.button.fontFamily',
    type: 'fontFamily',
  },
  'components.button.borderRadius': {
    alias: 'borderRadius',
    legacyPath: 'components.button.borderRadius',
    sourcePath: 'components.button.borderRadius',
    type: 'dimension',
  },
  'components.button.focus.outlineColor': {
    alias: 'colors.focus',
    legacyPath: 'components.button.focus.outlineColor',
    sourcePath: 'components.button.focus.outlineColor',
    type: 'color',
  },
  'components.button.focus.inverseOutlineColor': {
    alias: 'colors.focusInverse',
    legacyPath: 'components.button.focus.inverseOutlineColor',
    sourcePath: 'components.button.focus.inverseOutlineColor',
    type: 'color',
  },
  'components.button.size.small.fontSize': {
    alias: 'typeScale.size01.fontSize',
    legacyPath: 'components.button.size.small.fontSize',
    sourcePath: 'components.button.size.small.fontSize',
    type: 'dimension',
  },
  'components.button.size.small.height': {
    alias: 'spaceScale.spacing07',
    legacyPath: 'components.button.size.small.height',
    sourcePath: 'components.button.size.small.height',
    type: 'dimension',
  },
  'components.button.size.small.letterSpacing': {
    alias: 'typeScale.size01.letterSpacing',
    legacyPath: 'components.button.size.small.letterSpacing',
    sourcePath: 'components.button.size.small.letterSpacing',
    type: 'dimension',
  },
  'components.button.size.small.lineHeight': {
    alias: 'typeScale.size01.lineHeight',
    legacyPath: 'components.button.size.small.lineHeight',
    sourcePath: 'components.button.size.small.lineHeight',
    type: 'dimension',
  },
  'components.button.size.small.minWidth': {
    cssValue: '0px',
    legacyPath: 'components.button.size.small.minWidth',
    sourcePath: 'components.button.size.small.minWidth',
    type: 'dimension',
  },
  'components.button.size.small.paddingBlock': {
    alias: 'spaceScale.spacing02',
    legacyPath: 'components.button.size.small.paddingBlock',
    sourcePath: 'components.button.size.small.paddingBlock',
    type: 'dimension',
  },
  'components.button.size.small.paddingInline': {
    alias: 'spaceScale.spacing03',
    legacyPath: 'components.button.size.small.paddingInline',
    sourcePath: 'components.button.size.small.paddingInline',
    type: 'dimension',
  },
  'components.button.size.medium.fontSize': {
    alias: 'typeScale.size03.fontSize',
    legacyPath: 'components.button.size.medium.fontSize',
    sourcePath: 'components.button.size.medium.fontSize',
    type: 'dimension',
  },
  'components.button.size.medium.height': {
    alias: 'spaceScale.spacing09',
    legacyPath: 'components.button.size.medium.height',
    sourcePath: 'components.button.size.medium.height',
    type: 'dimension',
  },
  'components.button.size.medium.lineHeight': {
    alias: 'typeScale.size03.lineHeight',
    legacyPath: 'components.button.size.medium.lineHeight',
    sourcePath: 'components.button.size.medium.lineHeight',
    type: 'dimension',
  },
  'components.button.size.medium.minWidth': {
    alias: 'spaceScale.spacing13',
    legacyPath: 'components.button.size.medium.minWidth',
    sourcePath: 'components.button.size.medium.minWidth',
    type: 'dimension',
  },
  'components.button.size.medium.paddingBlock': {
    alias: 'spaceScale.spacing04',
    legacyPath: 'components.button.size.medium.paddingBlock',
    sourcePath: 'components.button.size.medium.paddingBlock',
    type: 'dimension',
  },
  'components.button.size.medium.paddingInline': {
    alias: 'spaceScale.spacing05',
    legacyPath: 'components.button.size.medium.paddingInline',
    sourcePath: 'components.button.size.medium.paddingInline',
    type: 'dimension',
  },
  'components.button.size.large.fontSize': {
    alias: 'typeScale.size04.fontSize',
    legacyPath: 'components.button.size.large.fontSize',
    sourcePath: 'components.button.size.large.fontSize',
    type: 'dimension',
  },
  'components.button.size.large.height': {
    alias: 'spaceScale.spacing11',
    legacyPath: 'components.button.size.large.height',
    sourcePath: 'components.button.size.large.height',
    type: 'dimension',
  },
  'components.button.size.large.lineHeight': {
    alias: 'typeScale.size04.lineHeight',
    legacyPath: 'components.button.size.large.lineHeight',
    sourcePath: 'components.button.size.large.lineHeight',
    type: 'dimension',
  },
  'components.button.size.large.minWidth': {
    alias: 'spaceScale.spacing13',
    legacyPath: 'components.button.size.large.minWidth',
    sourcePath: 'components.button.size.large.minWidth',
    type: 'dimension',
  },
  'components.button.size.large.paddingBlock': {
    alias: 'spaceScale.spacing04',
    legacyPath: 'components.button.size.large.paddingBlock',
    sourcePath: 'components.button.size.large.paddingBlock',
    type: 'dimension',
  },
  'components.button.size.large.paddingInline': {
    alias: 'spaceScale.spacing06',
    legacyPath: 'components.button.size.large.paddingInline',
    sourcePath: 'components.button.size.large.paddingInline',
    type: 'dimension',
  },
};
